config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'

  get 'teachers/show'

  get 'teachers/approve'

  get 'proposals/approve'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :proposals do
    resources :motivations do
      post :approve
    end
    get :approved
  end
  put 'proposals/:id/approved' => 'proposals#approved'

  resources :admins

  root 'pages#start'
end

app/views/admins/edit.html.slim
h1 =@user.name
p.lead =@user.email
p Roles

= form_for(@user, url: admin_path, method: :put) do |f|
  .checkbox
    = f.label :teacher do
      = f.check_box :teacher
      = :Teacher
    br
    = f.label :admin do
      = f.check_box :admin
      = :Admin

  = f.submit :update, class: 'btn btn-primary'

app/views/admins/index.html.erb
<div id="admin">
  <h1>Admin</h1>
  <div class="row">
    <div class="col-xs-4">
      <label for="admin-search">Search user:</label>
      <input class="form-control light-table-filter" type="search" data-table="order-table" id="admin-search" placeholder="Search">
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12">
      <table data-role="table" class="table table-hover order-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th class="center">Teacher</th>
            <th class="center">Admin</th>
          </tr>
        </thead>
        <tbody class="order-table-body">
          <% @users.each do |user| %>
          <tr data-id="<%= edit_admin_url(user.id) %>">
            <td><%= user.firstname %>
              <%= user.lastname %></td>
            <td><%= user.email %></td>
            <td class="center"><%= "√" if user.teacher? %></td>
            <td class="center"><%= "√" if user.admin? %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">
  (function (document) {
    'use strict';

    var LightTableFilter = (function (Arr) {

      var _input;

      function _onInputEvent(e) {
        _input = e.target;
        var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
        Arr.forEach.call(tables, function (table) {
          Arr.forEach.call(table.tBodies, function (tbody) {
            Arr.forEach.call(tbody.rows, _filter);
          });
        });
      }

      function _filter(row) {
        var text = row.textContent.toLowerCase(),
          val = _input.value.toLowerCase();
        row.style.display = text.indexOf(val) === -1
          ? 'none'
          : 'table-row';
      }

      return {
        init: function () {
          var inputs = document.getElementsByClassName('light-table-filter');
          Arr.forEach.call(inputs, function (input) {
            input.oninput = _onInputEvent;
          });
        }
      };
    })(Array.prototype);

    document.addEventListener('readystatechange', function () {
      if (document.readyState === 'complete') {
        LightTableFilter.init();
      }
    });

  })(document);
</script>

app/views/admins/index.html.slim
#admin
  h1 Admin
  .row
    .col-xs-4
      label for="admin-search" Search user:
      input#admin-search.form-control.light-table-filter type="search" data-table="order-table" placeholder="Search"

  br
  .row
    .col-xs-12
      table.table.table-hover.order-table data-role="table"
        thead
          tr
            th Name
            th Email
            th.center Teacher
            th.center Admin

        tbody.order-table-body
          - @users.each do |user|
            tr data-id = edit_admin_url(user.id)
              td = user.name
              td = user.email
              td.center = "√" if user.teacher?
              td.center = "√" if user.admin?

javascript:
  (function (document) {
    'use strict';

    var LightTableFilter = (function (Arr) {

      var _input;

      function _onInputEvent(e) {
        _input = e.target;
        var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
        Arr.forEach.call(tables, function (table) {
          Arr.forEach.call(table.tBodies, function (tbody) {
            Arr.forEach.call(tbody.rows, _filter);
          });
        });
      }

      function _filter(row) {
        var text = row.textContent.toLowerCase(),
          val = _input.value.toLowerCase();
        row.style.display = text.indexOf(val) === -1
          ? 'none'
          : 'table-row';
      }

      return {
        init: function () {
          var inputs = document.getElementsByClassName('light-table-filter');
          Arr.forEach.call(inputs, function (input) {
            input.oninput = _onInputEvent;
          });
        }
      };
    })(Array.prototype);

    document.addEventListener('readystatechange', function () {
      if (document.readyState === 'complete') {
        LightTableFilter.init();
      }
    });

  })(document);

app/views/admins/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>