config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'

  get 'teachers/show'

  get 'teachers/approve'

  get 'proposals/approve'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :proposals do
    resources :motivations do
      post :approve
    end
    get :approved
  end
  put 'proposals/:id/approved' => 'proposals#approved'

  resources :admins

  root 'pages#start'
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  scope :approved, -> { where(approved: true) }
  scope :pending, -> { where(approved: false) }

  belongs_to :user
  has_many :participants
  has_many :motivations

  def self.search(query)
     where("name like ?","%#{query}%").all
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  before_action :authenticate, except: [:index, :show]

  def index
    unless params[:search]
      @proposals = Proposal.approved.order("created_at desc").paginate(page: params[:page], per_page: 10)
    else
      @proposals = Proposal.search(params[:search]).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    end
    if signed_in?
      @myproposals = current_user.proposals
    end
  end

  def new
    @newproposal = Proposal.new
    @page = params[:page]
  end

  def edit
    @editproposal = Proposal.find(params[:id])
    unless (current_user.id == @editproposal.user_id) or (current_user.try(:teacher?))
      flash[:error] = "You are not allowed to edit this!"
      redirect_to proposal_url(@editproposal)
    end
  end

  def approve
    @proposals = Proposal.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def approved
    if current_user.try(:teacher?)
      @approvedproposal = Proposal.find(params[:id])
      @approvedproposal.approved = true
      @approvedproposal.save

      UserMailer.approved_email(current_user.name, @approvedproposal).deliver_now

      flash[:success] = "Proposal approved!"
      redirect_to proposals_approve_path
    else
      flash[:error] = "Error, you don't have permission to approve"
      redirect_to root_url
    end
  end

  def destroy
    @deleteproposal = Proposal.find(params[:id])
    if (current_user.try(:teacher?)) or (@deleteproposal.user_id == current_user.id)
      if (!current_user.try(:teacher?)) and (@deleteproposal.approved?)
        flash[:error] = "Error, you don't have permission to remove at this stage"
        redirect_to root_url
      else
        session[:return_to] ||= request.referer
        @deleteproposal = Proposal.find(params[:id])
        UserMailer.declined_email(current_user.name, @deleteproposal).deliver_now
        @deleteproposal.destroy
        flash[:success] = "Proposal removed!"
        redirect_to session.delete(:return_to)
      end
    else
      flash[:error] = "Error, you don't have permission to remove"
      redirect_to root_url
    end
  end

  def update
    @proposal = Proposal.find(params[:id])
    if (current_user.try(:teacher?)) or (@proposal.user_id == current_user.id)
      if @proposal.update_attributes(proposal_params)
        redirect_to proposal_url(@proposal)
        flash[:success] = "Proposal edited with no errors"
      else
        render 'edit'
        flash[:error] = "An error occured, please try again!"
      end
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
    @username = @proposal.user.email
    @all_motivations = Motivation.where(proposal_id: params[:id])
    @motivation =  @proposal.motivations.build
    @participants = @proposal.participants
  end

def create
  if signed_in?
    @proposal = current_user.proposals.build(proposal_params)
    @proposal.approved = false

    if @proposal.save
      redirect_to proposals_url
      UserMailer.proposal_submitted(@proposal).deliver_now
      flash[:success] = "Proposal submited with no errors"
    else
      render :new
      flash[:error] = "An error occured, please try again!"
    end
  else
    flash[:error] = "Please log in first"
    redirect_to new_user_session_path
  end
end

private

  def proposal_params
    params.require(:proposal).permit(:name, :description, :category, :course, :vsc_url, :project_managment_service)
  end

  def authenticate
    unless signed_in?
      flash[:error] = "Please log in first"
      redirect_to new_user_session_path
    end
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
  def correct_user
    user == current_user
  end

  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/views/proposals/approve.html.erb
<div id="approve">
    <h2>Approve
        <span class="spans">I</span>t</h2>
    <div class="row">
        <div class="col-xs-4">
            <label for="admin-search">Search proposal:</label>
            <input class="form-control light-table-filter" type="search" data-table="order-table" id="admin-search" placeholder="Proposal">
        </div>
    </div>
    <div class="row colortest">
        <h2>Approve projects</h2>
        <table class="table table-hover order-table" id="approve-proposals" data-role="table">
            <thead>
                <tr>
                    <th class="col-md-3">Name</th>
                    <th class="col-md-4">Description</th>
                    <th class="col-md-3">Category</th>
                    <th class="col-md-1 center">Approve</th>
                    <th class="col-md-1 center">Remove</th>
                </tr>
            </thead>
            <tbody>
                <% @proposals.each do |p| %>
                <% unless p.approved? %>
                <tr data-link="<%= proposal_path(p) %>">
                    <td class="col-md-3 clickable"><%= p.name %></td>
                    <td class="col-md-4 clickable breakable"><%= truncate(p.description, length: 50) %></td>
                    <td class="col-md-3 clickable"><%= p.category %></td>
                    <td class="col-md-1 centered"><%= link_to ('<i id="acceptglyph" class="glyphicon glyphicon-ok"></i>').html_safe, proposal_approved_path(p), method: :put, data: {:confirm => 'Are you sure?'} %></td>
                    <td class="col-md-1 centered"><%= link_to ('<i id="removeglyph" class="glyphicon glyphicon-remove"></i>').html_safe, p, data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
                </tr>
                <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<%= will_paginate @proposals, renderer: BootstrapPagination::Rails, previous_label: "«", next_label:"»", inner_window:1, outer_window: 1 %>
<script type="text/javascript">
    $(".clickable").click(function () {
        window.location = $(this).parent().data("link")
    });
</script>

app/views/proposals/edit.html.erb
<div id="edit">
  <h2>Edit
    <span>I</span>t</h2>

  <%= form_for @editproposal, :html => {:class => "form-horizontal "} do |f| %>
  <% unless @editproposal.approved && !current_user.teacher?%>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :title, "*Title: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :description, "*Description: ", class: "control-label"%>
    </div>
    <div class="col-md-6">
      <%= f.text_area :description, class: "form-control", required: true  %>
    </div>
  </div>
  <hr class="edit_hr">
  <p>Student specific</p>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :course, "Course: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :course, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :category, "Category: ", class: "control-label"%>
    </div>
    <div class="col-md-2">
      <%= f.select(:category, options_for_select([['Thesis', 'Thesis'], ['Candidate', 'Candidate'],['Bachelor', 'Bachelor']]), {}, {class: "form-control"}) %>
    </div>
  </div>
  <hr class="edit_hr">
  <p>Company specific</p>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :company, "Company name: ", class: "control-label"%>
    </div>
    <div class="col-md-6">
      <%= f.text_field :company, class: "form-control" %>
    </div>
  </div>
  <hr class="edit_hr">
  <% end %>
  <p>Workflow</p>
  <div class="form-group">
    <div class="col-md-3">
      <%= f.label :vcs_url, "VCS url: ", class: "control-label"%>
    </div>
    <div class="col-md-6">
      <%= f.text_field :vsc_url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group ">
    <div class="col-md-3">
      <%= f.label :project_managment_service, "Management Service url: ", class: "control-label"%>
    </div>
    <div class="col-md-6">
      <%= f.text_field :project_managment_service, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/proposals/index.html.erb
<div id="browse">
  <div class="row">
    <h2>Browse
      <span class="spans">I</span>t</h2>
    <br>
  </div>
  <% if current_user != nil %>
  <% unless current_user.proposals.count < 1 %>
  <h3 class="center">My projects</h3>
  <div class="row colortest">

    <table class="table table-hover" id="browse-own-proposals" data-role="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th class="center">Category</th>
          <th class="center">Remove</th>
          <th class="center">Approved</th>
        </tr>
      </thead>
      <tbody>
        <% @myproposals.each do |p| %>
        <% if p.user_id == current_user.id %>
        <tr data-link="<%= proposal_path(p) %>">
          <td><%= p.name %></td>
          <td class="breakable"><%= truncate(p.description, length: 120) %></td>
          <td class="center"><%= p.category %></td>
          <td class="center"><%= link_to ('<i id="removeglyph" class="glyphicon glyphicon-remove"></i>').html_safe, p, data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
          <% if p.approved %>
          <td class="center">
            <i class="glyphicon glyphicon-ok"></i>
          </td>
        <% else %>
          <td class="center">
            <i class="glyphicon glyphicon-time"></i>
          </td>
          <% end %>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
  <% end %>
  <div class="row center">
    <br>
    <h3>All approved projects</h3>
    <div class="col-sm-offset-8 col-sm-4">
      <div class="filter-proposals form-inline">
        <%= form_tag(proposals_path, :method => "get", id: "search-form") do %>

        <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Search project name" %>
        <%= submit_tag "Search", :class => "btn btn-primary", :name => nil %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row colortest">
    <table class="table table-hover order-table" id="browse-proposals" data-role="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th class="center">Category</th>
          <% if current_user.try(:teacher?) %>
          <th class="center">Remove</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @proposals.each do |p| %>
        <% if p.approved? %>
        <tr data-link="<%= proposal_path(p) %>">
          <td><%= p.name %></td>
          <td class="breakable"><%= truncate(p.description, length: 120) %></td>
          <td class="center"><%= p.category %></td>
          <% if current_user.try(:teacher?) %>
          <td class="center"><%= link_to ('<i id="removeglyph" class="glyphicon glyphicon-remove"></i>').html_safe, p, data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
          <% end %>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @proposals, renderer: BootstrapPagination::Rails, previous_label: "«", next_label:"»", inner_window:1, outer_window: 1 %>
</div>
<script type="text/javascript">
  $("table tbody tr").click(function () {
    window.location = $(this).data("link")
  });
</script>

app/views/proposals/new.html.erb
<div id="submit">
  <h2>Submit
    <span class="spans">I</span>t</h2>
  <br>

  <%= form_for @newproposal, :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :title, "Title: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :description, "Description: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.text_area :description, class: "form-control", required: true  %>
    </div>
  </div>

  <% if @page == "student" %>

  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :course, "Course: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :course, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :category, "Category: ", class: "control-label" %>
    </div>
    <div class="col-md-6">
      <%= f.select(:category, options_for_select([['Thesis', 'Thesis'], ['Candidate', 'Candidate'],['Bachelor', 'Bachelor']]), {}, { class: "form-control" }) %>
    </div>
  </div>

<% else %>

  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :company, "Company name: ", class: "control-label"%>
    </div>
    <div class="col-md-6">
      <%= f.text_field :company, class: "form-control", required: true %>
    </div>
  </div>
  <br>

  <% end %>

  <div class="row " id="submit_button">
    <div class="col-md-6 col-md-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<% if signed_in? %>
<% if (@proposal.user_id == current_user.id) or (current_user.try(:teacher?)) %>
<%= link_to 'Edit', edit_proposal_path(@proposal) %>
<% end %>
<% end %>
<h1><%= @proposal.name %></h1>
<% if !current_user.try(:company?) and signed_in? and @proposal.approved?%>
<div class="pull-right">
  <a class="btn btn-primary" id="apply_project" href="">Apply for project
    <span class="caret"></span>
  </a>
  <div class="" id="apply_form">
    <%= form_for [@proposal, @motivation], :html => { :class => "form-horizontal" } do |f| %>
    <div class="form-group">
      <div class="row">
        <%= f.label :motivation, "Motivation: ", class: "control-label" %>
      </div>
      <div class="row">
        <%= f.text_area :motivation, class: "form-control", required: true %>
      </div>
    </div>
    <div class="row" id="submit_button">
      <%= f.submit "Apply", class: "col-md-12 btn btn-default btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<%end%>
<h2><%= @username %></h2>
<small>Submitted at:
  <b>
    <%= @proposal.created_at %>
  </b>
</small>
<br>
<small>Participants:
  <% @participants.each do |participant| %>
  <%= "<b>#{participant.user.name} </b>(#{participant.user.email}) ".html_safe %>
  <% end %>
</small>
<hr>
<div class="row">
  <div >
    <div class="col-md-1">
      <strong>Description:</strong>
    </div>
    <br>
  </div>
  <div>
    <div class="col-md-10">
      <%= @proposal.description %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div id="github">
      <% unless @proposal.vsc_url.blank? %>
      <div class="col-md-2">
        <%= link_to ('<i class="glyphicon glyphicon-book"></i><br>Follow the projects VCS.').html_safe, url_with_protocol(@proposal.vsc_url), :target => '_blank' %>
        <% end %>
      </div>
    </div>
    <div id="trello">
      <% unless @proposal.project_managment_service.blank? %>
      <div class="col-md-2">
        <%= link_to ('<i class="glyphicon glyphicon-dashboard"></i><br>Follow the projects Management Service.').html_safe, url_with_protocol(@proposal.project_managment_service), :target => '_blank' %>
        <% end %>
      </div>
    </div>
    <div class="row" id="trello">
      <% unless @username.blank? %>
      <div class="col-md-2">
        <%= link_to ('<i class="glyphicon glyphicon-envelope"></i><br>Contact the project owner.').html_safe, 'mailto:' + @username + '?Subject=TrackIT%20Email%20Service' %>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user.try(:teacher) %>
    <div class="row colortest">
      <h2>Approve students for projects</h2>
      <table class="table table-hover order-table" id="approve-proposals" data-role="table">
        <thead>
          <tr>
            <th class="col-md-3">Name</th>
            <th class="col-md-4">Motivation</th>
            <th class="col-md-1 center">Accept</th>
            <th class="col-md-1 center">Decline</th>
          </tr>
        </thead>
        <tbody>
          <% if @all_motivations.count > 0 %>
          <% @all_motivations.each do |m| %>
          <td class="col-md-4 clickable"><%= "#{m.user.name}  (#{m.user.email})" %></td>
          <td class="col-md-4 clickable breakable"><%= truncate(m.motivation, length: 50) %></td>
          <td class="col-md-1 centered"><%= link_to ('<i id="acceptglyph" class="glyphicon glyphicon-ok"></i>').html_safe, proposal_motivation_approve_path(m.proposal, m), method: :post, data: { confirm: 'Are you sure?' } %></td>
          <td class="col-md-1 centered"><%= link_to ('<i id="removeglyph" class="glyphicon glyphicon-remove"></i>').html_safe, proposal_motivation_path(m.proposal, m), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>