config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'

  get 'teachers/show'

  get 'teachers/approve'

  get 'proposals/approve'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :proposals do
    resources :motivations do
      post :approve
    end
    get :approved
  end
  put 'proposals/:id/approved' => 'proposals#approved'

  resources :admins

  root 'pages#start'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/">Track<span class="spans">I</span>t</a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li class="<%= is_active?('/') %>"><%= link_to "Home", '/' %></li>

    <% if signed_in? %>
    <li class="<%= is_active?('/proposals/new?page=student') %><%= is_active?('/proposals/new?page=company') %> dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Submit <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li class="<%= is_active?(new_proposal_path + '?page=student') %>"><%= link_to "Student submit", new_proposal_path + '?page=student' %></li>
        <li class="<%= is_active?(new_proposal_path + '?page=company') %>"><%= link_to "Company submit", new_proposal_path + '?page=company' %></li>
      </ul>
    </li>
    <% else %>
      <li class="<%= is_active?(proposals_path) %><%= is_active?(proposals_approve_path) %>"><%= link_to "Submit", new_user_session_path %></li>
    <% end %>

    <li class="<%= is_active?(proposals_path) %>"><%= link_to "Browse", proposals_path, method: :get %></li>
    <% if current_user.try(:teacher?) %>
      <li class="<%= is_active?(proposals_approve_path) %>"><%= link_to "Approve", proposals_approve_path, method: :get %></li>
    <% end %>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="<%= is_active?(edit_user_registration_path) %>"><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li class="<%= is_active?(new_proposal_path + '?page=company') %>"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to 'Sign in / Sign up', new_user_session_path %></li>
    <% end %>
  </ul>

</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackIT2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-signed-in="<%= signed_in? %>">

    <%= render 'layouts/navigation' %>

    <div class="container">

      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <div class="jumbotron">
        <%= yield %>
      </div>

    </div>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 center">
            <p class="text-muted">KONTAKT Tel: +46 40 665 70 00 Malmö högskola 205 06 Malmö Sweden
            </p>
            <a href="#">Example@mah.se</a>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title TrackIT2
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body data-signed-in=(signed_in? ? "true" : "false")
    = render 'layouts/navigation'

    .container
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-#{key}"

      .jumbotron
        = yield

  footer.footer
    .container
      .row
        .col-xs-12.center
          p.text-muted
            ' Kontakt tel: +46 40 665 70 00 Malmö Högskola 205 06 Malmö Sweden
            a href="#" Example@mah.se